[scripts]
runb = ["python", "-m", "backend.src.main"]
testenv = ["python", "-m", "backend.src.utils.testenv"]
activate = ["backend\\venv\\Scripts\\activate"]
deactivate = ["backend\\venv\\Scripts\\deactivate.bat"]
run = ["flask", "--debug", "--app", "backend/src/main", "run"]
migrate = ["python", "-m", "backend.src.utils.migrator"]
makepass = ["python", "-m", "backend.src.utils.makepass"]
makepid = ["python", "-m", "backend.src.utils.makepid"]
serve = ["npx", "serve", "-s", "build"]